{% set name = "gridstack.js" %}
{% set version = "0.6.2" %}
{% set sha256 = "dcb2b6dd04d2069f7c4027ca1a233d5b8db661e0e2719a5e75e05f9f0b7120c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gridstack/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g gridstack
  requires:
    - nodejs
   

about:
  home: https://github.com/gridstack/gridstack.js
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'gridstack.js is a jQuery plugin for widget layout'
  description: |
    gridstack.js is a mobile-friendly Javascript library for dashboard layout and 
    creation. Making a drag-and-drop, multi-column dashboard has never been easier. 
    gridstack.js allows you to build draggable, responsive bootstrap v3-friendly 
    layouts. It also works great with knockout.js, angular.js, ember. 
  doc_url: https://github.com/gridstack/gridstack.js
  dev_url: https://github.com/gridstack/gridstack.js

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
