travis:
  secure:
    BINSTAR_TOKEN: fXxdGP/A+8RuAc9POGy9P+klIx5htj9CVUGId36/NdCc2w5DKlBrrPZsmuKluHHMyitdMyrCBRwW/Y3yKL8zD1GU+OZd1aTgtE6IBfUwH5YdKSS157W6K8Bl2AkcURuTvJbvnmUiF8xbtfVFPRJzXVRfVFJphPEo30suBgarDthR0+cYGxCZSw+kBm8IPVIkj94BKHG6J8iGntVOpiZYO4zJChrRUJkJVQH1TSWU+S6b7Fnkq8TFce/oUuD6v6Qwek7klUzumSsWcn/BcV6FP3VrgrPzuJ7a+5SJBJz+mnzFR34Mkk6459H0Nqr15/4pXxp+bYFbHqd2hE/FDiL/k//hChSUXglSoBasB0jBBgpGLxcZ4mnmJog4nyAno5GbA2C7x1YzwYLHn7O7FCz+61HMbNEmQWNL+BfDEcwzutx4oBNEL/gwt08P3YF4DNLnE4Bs7zYQ27/6dkwvVApx8+amXG+y//Bxhpp0PJPLn7b5GqjiF+mE8piPdf4nfV9Y+Cu5dJzAZNVXmhYVlOJ11yfChgQLYY0a/KGCi9R0ZibemA4XMJDNsYYnf5QO+Wp6zzcY/hBfARbgwx+fgAH6pio9vWBrDrC9Ohwufa61UrJuoJ2SHSFFOwPrXSt3QN4b73AhDwuzqVHd9tKBSnSlgBNCdS9EQsGlXb8OrS0TOlU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
