travis:
  secure:
    BINSTAR_TOKEN: pQvFWlM3V/fERHfNDPVqGIabFfr4gYwmO1oOLAZXA7zWynmErdz5U4dS8ERuTvFEEb52DkQGHThIfbpRQGvPIckg2zEkMfeJZ2t6QLD3HToZkpsQEOf/QuOtfR2Xz8My+DEJkWZ9uxUyg0LYmw4OTxOYnwJTV48So1CLzrizGrRJhZYqxA6IUuE8PuUBtgN9vGH+f9+CHETBPGMv1QyhPCqi5mtTUAoEtQ2BLnWTZDgFvY0KYqvzlvnScqRk8BxOLjNREWWBSraQ8ODR+Hi2yo3/KANU6RjWtye+dxgZw3q6a8oinRtMJ5lCfjGA0fKaN2ggi4M5OOPR2iFPzAcO2waW1zi2n2Thpcs0w33R804yRoeRjPRowRbC1k33zBmKQuM0JH7igxPSWnOwiJE5Pax/+9ifH6bZRuorC8/6phTGLRKmHNtsuw/aVRFnBqthvRNxtYNyNREJFqgcTLMghyULzePOeUg4swaem+oVyD302asYuwJ13tbX9qhol0MsNGvDf7bZgwlSug+GneEwW7g/hYrEuJsc90mNmktUzTdK7MXu6cBzr+RSMoQHIFFrzHa57chzWTJwCUvyZjxO1KefbaaLl+Vc8f4t1d/ZNDqVixcBQDnDlHygMU9WmdSHxZqSpjejmcMtelCuX0E7oBQZyI1d2FW9+47/tflJzYA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
