travis:
  secure:
    BINSTAR_TOKEN: HKv9bkwgqZZaTzLOpd404ltY9kjwEQRXQOWM8h+VZoZMp2eDnIJq9ZuIWRDwMEFMDGeHwe/VRdg8+2wudDisEEvlq6G3x1ZVxK6pxkFEnHbCjW84dF64WdGklrX9WJGKBdoO1bgf0gZkB7Oawp//bCoG6biT7p5UAquRbrdNw/3vmLwr07F8gfQZbN+IpjALJa6v4o1QORII5ZqXjAcj4HhWoc34ZauqgJOYWILDj/p7yOMl7a5f3sha8GKGF2FJoksS4UfHncSuzB83xlsf/l9/buEAOIe71jGLrD09w97ZQzowwFpYxDOtsodaY5aWVRYkJjyhhzkgWwjtLuYbpv2srNXBgTeyAXS0mWwQle1nh92j3Dks/0FaGe3GsJ7WJylr1SeRS3Al5X5XQcRQ22DK7TpUA5BOTMuU+NdQQSxln1DaZkBs2W/WFBlQpG2ZCcpydirg52OO/GoNKXIuLs3jo9u/WsO5tSFqmZhEIVcoLIfHMgCrJbRcyuosxbHfGqK296MvyCgma/TbrGpynWefD2u0McRn4e9Ui8AiZY6TfJ8pVVPbBPQGJ2Tx9/wDKe2BdSiBpGxWL574KX/1VYGdZdZiWRDsze4ftMFFSpdD4aQbV6mfN1xaI9v78AWLsfSHXG2UW2oOlpmDeA1BXb6BYFqlgrUyHAJ70EMIm4I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
